name: flix_id
description: "Flutter Udemy Course"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  flutter:
    sdk: flutter
  freezed_annotation: null
  go_router: ^14.4.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: null
  path: ^1.9.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: null
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_riverpod: ^2.6.1
  flutter_test:
    sdk: flutter
  freezed: null
  json_serializable: null
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
